WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER=XEPDB1;
CREATE TABLE KAIRO_LAB.KAIRO_LOB_REVIEW_0908 (
  ID NUMBER PRIMARY KEY,
  BODY CLOB,
  LABEL VARCHAR2(80),
  BIN BLOB,
  NATIONAL NCLOB
);
INSERT INTO KAIRO_LAB.KAIRO_LOB_REVIEW_0908 VALUES (1,NULL,'null',NULL,NULL);
INSERT INTO KAIRO_LAB.KAIRO_LOB_REVIEW_0908 VALUES (2,EMPTY_CLOB(),'empty',EMPTY_BLOB(),EMPTY_CLOB());
DECLARE
  c CLOB; b BLOB; n NCLOB;
  txt VARCHAR2(100) := UNISTR('\4E2D\6587\D83D\DE00') || CHR(10) || 'lob-';
  ntxt NVARCHAR2(100) := UNISTR('\4E2D\6587\D83D\DE00') || CHR(10) || 'lob-';
  rawval RAW(16) := HEXTORAW('000A0DFF80414243');
BEGIN
  FOR i IN 3..9 LOOP
    INSERT INTO KAIRO_LAB.KAIRO_LOB_REVIEW_0908 VALUES (i,EMPTY_CLOB(),'boundary-' || i,EMPTY_BLOB(),EMPTY_CLOB())
      RETURNING BODY,BIN,NATIONAL INTO c,b,n;
    FOR j IN 1..CASE i WHEN 3 THEN 1 WHEN 4 THEN 512 WHEN 5 THEN 4096 WHEN 6 THEN 8192 WHEN 7 THEN 16384 WHEN 8 THEN 65536 ELSE 131072 END LOOP
      DBMS_LOB.WRITEAPPEND(c,LENGTH2(txt),txt);
      DBMS_LOB.WRITEAPPEND(n,LENGTH2(ntxt),ntxt);
      DBMS_LOB.WRITEAPPEND(b,UTL_RAW.LENGTH(rawval),rawval);
    END LOOP;
  END LOOP;
END;
/
GRANT SELECT, UPDATE ON KAIRO_LAB.KAIRO_LOB_REVIEW_0908 TO KAIRO_RO;
COMMIT;
SELECT ID,DBMS_LOB.GETLENGTH(BODY),DBMS_LOB.GETLENGTH(BIN),DBMS_LOB.GETLENGTH(NATIONAL) FROM KAIRO_LAB.KAIRO_LOB_REVIEW_0908 ORDER BY ID;
EXIT
